export class EnglishResources {
  getResources() {
    return {
      locale: "en",
      reasonMessages: {
        english_only: "Use English animal names only, for example: dog, whale, eagle.",
        blocked_or_invalid: "That is not acceptable. Type a real animal, for example: dog, whale, eagle.",
        unclear: "I cannot learn from that. Type one clear animal name, for example: dog, whale, eagle.",
        default: "That does not look like an animal. Type a real animal, for example: dog, whale, eagle.",
      },
      debug: {
        noModelCallYet: "No model call yet.",
        noPromptYet: "No prompt yet.",
        noResponseYet: "No response yet.",
        emptyResponse: "[empty response]",
        engineNotReady: "The LLM provider is not ready.",
        promptEmpty: "Debug prompt is empty.",
        runningEditedPrompt: "Running edited debug prompt...",
        editedPromptCompleted: "Edited debug prompt completed.",
        promptFailed: (errorMessage) => `Debug prompt failed. ${errorMessage}`,
        stages: {
          healthCheck: "Health check",
          prompt0ValidateAnimalInput: "Prompt 0: validate animal input",
          prompt1GenerateQuestion: "Prompt 1: generate question",
          prompt15SameAnimalCheck: "Prompt 1.5: same animal check",
          prompt2ValidateQuestion: "Prompt 2: validate question",
          debugReplaySuffix: "debug replay",
        },
      },
      providers: {
        labels: {
          local: "local WebLLM provider",
          echo: "echo provider",
          openai: "OpenAI-compatible provider",
        },
        status: {
          loading: (providerLabel) => `Loading ${providerLabel}...`,
          connectingOpenAi: "Connecting to the OpenAI-compatible API...",
        },
        errors: {
          noProviderSelected: "No provider selected.",
          unknownProviderType: (providerType) => `Unknown provider type: ${providerType}`,
          openAiBaseUrlMissing: "OpenAI-compatible provider requires apiBaseUrl.",
          openAiApiKeyMissing: "OpenAI-compatible provider requires an API key.",
          openAiModelMissing: "OpenAI-compatible provider requires apiModel.",
          openAiRequestFailed: (status, details) => `OpenAI-compatible request failed with status ${status}. ${details}`,
          openAiInvalidResponse: "OpenAI-compatible provider returned an invalid response.",
        },
      },
      status: {
        waitingToStart: "Waiting to start...",
        loadingResources: "Loading resources...",
        checkingProviderStatus: "Checking provider status...",
        waitingForProvider: "Waiting for provider...",
        sendingHelloPrompt: "Sending hello prompt and waiting for the provider response...",
        readyToStartGame: "The provider is ready. Start the game when you are ready.",
        savedTreeReset: "The saved tree was reset.",
        modelReadyThinkAnimal: "The model is ready. Think of an animal and answer with yes or no.",
        sameAnimalDetected: "Same animal detected. The tree was not expanded.",
        learningHowToDistinguish: (knownAnimal, newAnimal) => `Learning how to distinguish ${knownAnimal} from ${newAnimal}...`,
        savedToLocalStorage: "Saved to local storage.",
        inconsistentAnimalNormalization: "The model returned an inconsistent animal normalization.",
        inputRejected: "The input was rejected.",
        loadingFallback: "Loading...",
        modelLoaded: "Model loaded.",
        checkingModelResponse: "Checking model response...",
        fallbackQuestionUsed: (errorMessage) => `The model did not return a clean question, so the game used a fallback question. ${errorMessage}`,
      },
      game: {
        localKnowledgeBaseReset: "The local knowledge base was reset.",
        savedTreeInvalid: "The saved tree looks invalid. Reset the page storage and try again.",
        guessedIt: (animalLabel) => `I guessed it. It is ${animalLabel}.`,
        unknownAnimalLost: "Then I do not know. I lost.",
        typeChosenAnimal: "Type the animal you chose.",
        sameAnimalCounts: "OK, that also counts. I guessed it!",
        inconsistentAnswer: "That answer looks inconsistent. Type one simple animal name in English.",
        savingNewQuestion: "Saving a new question...",
        savedNewQuestion: (question) => `Saved.\nNew question: ${question}`,
        guessedAnimalQuestion: (animalLabel) => `Is it ${animalLabel}?`,
        userYes: "Yes",
        userNo: "No",
        finished: {
          won: "You won.",
          lost: "You lost.",
          cancelled: "Game cancelled.",
          invalid: "Game finished with an invalid state.",
          closed: "The game session is closed. Press F5 to start again.",
        },
      },
      ui: {
        pageTitle: "Browser LLM Demo",
        pageDescription: "Minimal browser-only skeleton for loading an LLM provider and starting a tiny yes/no guessing game.",
        languageLabel: "Language",
        languages: {
          en: "English",
          de: "Deutsch",
        },
        restart: "Let's play again",
        startGameButton: "Start Game",
        debugStageLabel: "Stage",
        debugPromptLabel: "Prompt",
        debugResponseLabel: "Raw Response",
        debugSendAgain: "Send Again",
        debugButton: "Debug",
        resetBaseButton: "Reset Base",
        gameTitle: "Game",
        statusTitle: "Status",
        lastModelCallTitle: "Last Model Call",
        animalInputPlaceholder: "Type the animal name in English",
        yesButton: "Yes",
        noButton: "No",
        saveButton: "Save",
        gameTryAgainButton: "Try Again",
        gameCloseButton: "Close Game",
      },
      errors: {
        modelEngineNotReady: "The LLM provider is not ready.",
        modelDidNotReturnJson: "Model did not return a JSON object.",
        modelDidNotReturnYesNo: "Model did not return YES or NO.",
        modelReturnedEmptyQuestion: "Model returned an empty question.",
        modelReturnedUnexpectedAnimals: "Model returned unexpected animal names.",
        modelReturnedSameAnimals: "Model assigned the same animal to both branches.",
        validatorReturnedEmptyQuestion: "Validator returned an empty question.",
        modelReturnedEmptyHelloResponse: "Model returned an empty response to the hello check.",
        webGpuUnavailable: "WebGPU is not available in this browser. Try a recent Chrome, Edge, or another browser with WebGPU enabled.",
        fileProtocolUnsupported: "This page is being opened with file://. Run the demo from C:\\work-poc\\portfolio\\local-llm-browser with `python -m http.server 8080` and open http://localhost:8080.",
        remoteConfigFetchFailed: (modelUrl, errorMessage) => `Could not fetch remote model config from ${modelUrl}. Original error: ${errorMessage}`,
        remoteConfigUnavailable: (modelUrl) => `Remote model config is not reachable at ${modelUrl}/resolve/main/mlc-chat-config.json.`,
        remoteLibraryFetchFailed: (libraryUrl, errorMessage) => `Could not fetch ${libraryUrl}. Make sure model_lib.wasm exists and is reachable over HTTP. Original error: ${errorMessage}`,
        remoteLibraryUnavailable: (libraryUrl) => `Remote model library is not reachable at ${libraryUrl}.`,
      },
      prompts: {
        healthcheck: "hello",
        generateQuestion: (knownAnimal, newAnimal) => `You are a question generator for an animal guessing game.\n\nThe game needs one yes/no question that clearly distinguishes two animals.\n\nKnown animal:\n"${knownAnimal}"\n\nNew animal:\n"${newAnimal}"\n\nGenerate one short, general, factual question.\n\nRules:\n- The question must be answerable by "yes" or "no".\n- The question must separate the two animals reliably.\n- Prefer biological/category/physical/habitat traits.\n- Do NOT use animal-specific sounds like "Does it meow?" or "Does it bark?"\n- Do NOT mention either animal name directly.\n- Do NOT ask about subjective traits.\n- Do NOT ask about rare edge cases.\n- The question must be simple enough for a child.\n- Return only valid JSON.\n- Do not add explanations.\n\nBad examples:\n- "Does it meow?"\n- "Does it bark?"\n- "Is it cute?"\n- "Can it be a pet?"\n\nGood examples:\n- "Is it from the cat family?"\n- "Does it usually live in water?"\n- "Does it have hooves?"\n- "Is it a bird?"\n- "Does it have scales?"\n\nReturn format:\n{\n  "question": "...?",\n  "yesAnimal": "${knownAnimal} or ${newAnimal}",\n  "noAnimal": "${knownAnimal} or ${newAnimal}"\n}`,
        validateQuestion: (knownAnimal, newAnimal) => `You are a strict validator for an animal guessing game question.\n\nKnown animal:\n"${knownAnimal}"\n\nNew animal:\n"${newAnimal}"\n  \nDo not explain.\nthe answer for YOUR question should be\nYES - ${knownAnimal}\nNo - ${newAnimal}\n\ndo not use animal names in question\nRETURN only text of question`,
        sameAnimalCheck: (guessedAnimal, userAnimal) => `is "${guessedAnimal}" and "${userAnimal}" the same animal?\nsay yes or no\nno explanation\nno punctuation`,
        validateAnimalInput: (userInput) => `Decide whether the word "${userInput}" is a real common animal name.\nanswer YES if yes\nand NO if no\nNO explanation`,
      },
    };
  }
}
