export class EnglishResources {
  getResources() {
    return {
      locale: "en",
      debug: {
        noModelCallYet: "No model call yet.",
        noPromptYet: "No prompt yet.",
        noResponseYet: "No response yet.",
        emptyResponse: "[empty response]",
        engineNotReady: "The LLM provider is not ready.",
        promptEmpty: "Debug prompt is empty.",
        runningEditedPrompt: "Running edited debug prompt...",
        editedPromptCompleted: "Edited debug prompt completed.",
        promptFailed: (errorMessage) => `Debug prompt failed. ${errorMessage}`,
        stages: {
          healthCheck: "Health check",
          gameValidateAnimalInput: "Game: validate animal input",
          gameGenerateDistinguishingQuestion: "Game: generate distinguishing question",
          gameValidateGeneratedQuestion: "Game: validate generated question",
          debugReplaySuffix: "debug replay",
        },
      },
      providers: {
        labels: {
          local: "local WebLLM provider",
          echo: "echo provider",
          openai: "OpenAI-compatible provider",
        },
        status: {
          loading: (providerLabel) => `Loading ${providerLabel}...`,
          connectingOpenAi: "Connecting to the OpenAI-compatible API...",
        },
        errors: {
          noProviderSelected: "No provider selected.",
          unknownProviderType: (providerType) => `Unknown provider type: ${providerType}`,
          openAiBaseUrlMissing: "OpenAI-compatible provider requires apiBaseUrl.",
          openAiApiKeyMissing: "OpenAI-compatible provider requires an API key.",
          openAiModelMissing: "OpenAI-compatible provider requires apiModel.",
          openAiRequestFailed: (status, details) => `OpenAI-compatible request failed with status ${status}. ${details}`,
          openAiInvalidResponse: "OpenAI-compatible provider returned an invalid response.",
        },
      },
      status: {
        waitingToStart: "Waiting to start...",
        loadingResources: "Loading resources...",
        checkingProviderStatus: "Checking provider status...",
        waitingForProvider: "Waiting for provider...",
        sendingHelloPrompt: "Sending hello prompt and waiting for the provider response...",
        readyToStartGame: "The provider is ready. Start the game when you are ready.",
        loadingFallback: "Loading...",
        modelLoaded: "Model loaded.",
        checkingModelResponse: "Checking model response...",
      },
      game: {
        messages: {
          roundStarted: "Let us play. Think of an animal and I will try to guess it.",
          animalGuessQuestion: (animalLabel) => `Is it ${animalLabel}?`,
          branchQuestionFallback: "Answer yes or no.",
          lostAskAnimal: "I could not guess your animal. Which animal were you thinking of?",
          validatingAnimalInput: "Let me check that...",
          invalidAnimalInput: "Very funny. Give me one clear, common animal name in English, and make sure it is different from the animal I just guessed.",
          generatingQuestion: "Let me think about that...",
          validatingQuestion: "One moment, I am checking something...",
          savingLearning: "Almost done...",
        },
        finished: {
          won: "I guessed it!",
          lost: "I did not guess your animal this time.",
          cancelled: "Game cancelled.",
          invalid: "Something went wrong, so I had to stop this round. You can try again.",
          closed: "The game session is closed. Press F5 to start again.",
        },
      },
      ui: {
        pageTitle: "Browser LLM Demo",
        pageDescription: "Minimal browser-only skeleton for loading an LLM provider and starting a tiny yes/no guessing game.",
        languageLabel: "Language",
        languages: {
          en: "English",
          de: "Deutsch",
        },
        restart: "Let's play again",
        startGameButton: "Start Game",
        debugStageLabel: "Stage",
        debugPromptLabel: "Prompt",
        debugResponseLabel: "Raw Response",
        debugSendAgain: "Send Again",
        debugButton: "Debug",

        gameTitle: "Game",
        statusTitle: "Status",
        lastModelCallTitle: "Last Model Call",
        animalInputPlaceholder: "Type the animal name in English",
        yesButton: "Yes",
        noButton: "No",
        saveButton: "Save",
        gameTryAgainButton: "Try Again",
        gameCloseButton: "Close Game",
      },
      errors: {
        modelEngineNotReady: "The LLM provider is not ready.",
        modelDidNotReturnJson: "Model did not return a JSON object.",
        modelDidNotReturnYesNo: "Model did not return YES or NO.",
        modelReturnedEmptyQuestion: "Model returned an empty question.",
        modelReturnedUnexpectedAnimals: "Model returned unexpected animal names.",
        modelReturnedSameAnimals: "Model assigned the same animal to both branches.",
        validatorReturnedEmptyQuestion: "Validator returned an empty question.",
        modelReturnedEmptyHelloResponse: "Model returned an empty response to the hello check.",
        webGpuUnavailable: "WebGPU is not available in this browser. Try a recent Chrome, Edge, or another browser with WebGPU enabled.",
        fileProtocolUnsupported: "This page is being opened with file://. From the project directory, run `python -m http.server 8080` and open http://localhost:8080.",
        remoteConfigFetchFailed: (modelUrl, errorMessage) => `Could not fetch remote model config from ${modelUrl}. Original error: ${errorMessage}`,
        remoteConfigUnavailable: (modelUrl) => `Remote model config is not reachable at ${modelUrl}/resolve/main/mlc-chat-config.json.`,
        remoteLibraryFetchFailed: (libraryUrl, errorMessage) => `Could not fetch ${libraryUrl}. Make sure model_lib.wasm exists and is reachable over HTTP. Original error: ${errorMessage}`,
        remoteLibraryUnavailable: (libraryUrl) => `Remote model library is not reachable at ${libraryUrl}.`,
      },
      prompts: {
        healthcheck: "hello",
        game: {
          validateAnimalInput: (failedAnimalName, userInput) => `SYSTEM:\nYou validate user input for an animal guessing game.\n\nTASK:\nDecide whether USER_INPUT is:\n1. a real common animal name in English\n2. different from FAILED_ANIMAL_NAME\n\nRULES:\n- Accept only a common animal name in English.\n- Reject mythical creatures, jobs, objects, places, adjectives, or vague categories.\n- Reject if it is the same animal as FAILED_ANIMAL_NAME.\n- Prefer singular common names.\n- Return JSON only.\n- Do not add explanation outside JSON.\n\nINPUT:\nFAILED_ANIMAL_NAME: "${failedAnimalName}"\nUSER_INPUT: "${userInput}"\n\nRETURN JSON ONLY:\n{\n  "isValid": true,\n  "normalizedAnimal": "whale",\n  "reasonCode": "valid"\n}`,
          generateDistinguishingQuestion: (failedAnimalName, userAnimalName, previousQuestionsJson) => `SYSTEM:\nYou generate one yes/no question for an animal guessing game.\n\nTASK:\nCreate one short distinguishing yes/no question between FAILED_ANIMAL_NAME and NEW_ANIMAL_NAME.\n\nRULES:\n- The question must be answerable by yes or no.\n- The question must distinguish these two animals.\n- Do not mention either animal name in the question.\n- Prefer simple, stable, factual traits.\n- Avoid rare exceptions.\n- Avoid subjective wording.\n- Avoid duplicate or near-duplicate questions from PREVIOUS_QUESTIONS.\n- Return exactly one candidate mapping.\n- Return JSON only.\n\nINPUT:\nFAILED_ANIMAL_NAME: "${failedAnimalName}"\nNEW_ANIMAL_NAME: "${userAnimalName}"\nPREVIOUS_QUESTIONS:\n${previousQuestionsJson}\n\nRETURN JSON ONLY:\n{\n  "question": "Does it live in water?",\n  "yesAnimal": "whale",\n  "noAnimal": "cat"\n}`,
          validateGeneratedQuestion: (failedAnimalName, userAnimalName, candidateQuestion, declaredYesAnimal, declaredNoAnimal) => `SYSTEM:\nYou validate a candidate yes/no question for an animal guessing game.\n\nTASK:\nCheck whether CANDIDATE_QUESTION correctly distinguishes FAILED_ANIMAL_NAME and NEW_ANIMAL_NAME, and whether the yes/no mapping is valid.\n\nRULES:\n- The question must be a yes/no question.\n- The question must not contain animal names directly.\n- The question should clearly distinguish the two animals.\n- The declared yes/no mapping must be logically consistent.\n- Return JSON only.\n\nINPUT:\nFAILED_ANIMAL_NAME: "${failedAnimalName}"\nNEW_ANIMAL_NAME: "${userAnimalName}"\nCANDIDATE_QUESTION: "${candidateQuestion}"\nDECLARED_YES_ANIMAL: "${declaredYesAnimal}"\nDECLARED_NO_ANIMAL: "${declaredNoAnimal}"\n\nRETURN JSON ONLY:\n{\n  "isValid": true,\n  "normalizedQuestion": "Does it live in water?",\n  "yesAnimal": "whale",\n  "noAnimal": "cat",\n  "reasonCode": "valid"\n}`,
        },
      },
    };
  }
}
