export class GermanResources {
  getResources() {
    return {
      locale: "de",
      reasonMessages: {
        english_only: "Bitte verwende nur englische Tiernamen, zum Beispiel: dog, whale, eagle.",
        blocked_or_invalid: "Das ist nicht akzeptabel. Gib ein echtes Tier ein, zum Beispiel: dog, whale, eagle.",
        unclear: "Daraus kann ich nichts lernen. Gib einen klaren Tiernamen ein, zum Beispiel: dog, whale, eagle.",
        default: "Das sieht nicht wie ein Tier aus. Gib ein echtes Tier ein, zum Beispiel: dog, whale, eagle.",
      },
      debug: {
        noModelCallYet: "Noch kein Modellaufruf.",
        noPromptYet: "Noch kein Prompt.",
        noResponseYet: "Noch keine Antwort.",
        emptyResponse: "[leere Antwort]",
        engineNotReady: "Der LLM-Provider ist nicht bereit.",
        promptEmpty: "Der Debug-Prompt ist leer.",
        runningEditedPrompt: "Bearbeiteter Debug-Prompt wird ausgefuehrt...",
        editedPromptCompleted: "Bearbeiteter Debug-Prompt abgeschlossen.",
        promptFailed: (errorMessage) => `Debug-Prompt fehlgeschlagen. ${errorMessage}`,
        stages: {
          healthCheck: "Gesundheitspruefung",
          prompt0ValidateAnimalInput: "Prompt 0: Tiereingabe validieren",
          prompt1GenerateQuestion: "Prompt 1: Frage erzeugen",
          prompt15SameAnimalCheck: "Prompt 1.5: Gleiches Tier pruefen",
          prompt2ValidateQuestion: "Prompt 2: Frage validieren",
          debugReplaySuffix: "Debug-Wiederholung",
        },
      },
      providers: {
        labels: {
          local: "lokaler WebLLM-Provider",
          echo: "Echo-Provider",
          openai: "OpenAI-kompatibler Provider",
        },
        status: {
          loading: (providerLabel) => `${providerLabel} wird geladen...`,
          connectingOpenAi: "Verbindung zur OpenAI-kompatiblen API wird aufgebaut...",
        },
        errors: {
          noProviderSelected: "Kein Provider ausgewaehlt.",
          unknownProviderType: (providerType) => `Unbekannter Provider-Typ: ${providerType}`,
          openAiBaseUrlMissing: "Der OpenAI-kompatible Provider benoetigt apiBaseUrl.",
          openAiApiKeyMissing: "Der OpenAI-kompatible Provider benoetigt einen API-Schluessel.",
          openAiModelMissing: "Der OpenAI-kompatible Provider benoetigt apiModel.",
          openAiRequestFailed: (status, details) => `Die OpenAI-kompatible Anfrage ist mit Status ${status} fehlgeschlagen. ${details}`,
          openAiInvalidResponse: "Der OpenAI-kompatible Provider hat eine ungueltige Antwort geliefert.",
        },
      },
      status: {
        waitingToStart: "Wartet auf den Start...",
        loadingResources: "Ressourcen werden geladen...",
        checkingProviderStatus: "Provider-Status wird geprueft...",
        waitingForProvider: "Warte auf den Provider...",
        sendingHelloPrompt: "Hello-Prompt wird gesendet und auf die Antwort des Providers gewartet...",
        readyToStartGame: "Der Provider ist bereit. Starte das Spiel, wenn du bereit bist.",
        savedTreeReset: "Der gespeicherte Baum wurde zurueckgesetzt.",
        modelReadyThinkAnimal: "Das Modell ist bereit. Denke an ein Tier und antworte mit Ja oder Nein.",
        sameAnimalDetected: "Dasselbe Tier wurde erkannt. Der Baum wurde nicht erweitert.",
        learningHowToDistinguish: (knownAnimal, newAnimal) => `Ich lerne gerade, wie man ${knownAnimal} von ${newAnimal} unterscheidet...`,
        savedToLocalStorage: "In localStorage gespeichert.",
        inconsistentAnimalNormalization: "Das Modell hat eine inkonsistente Tier-Normalisierung zurueckgegeben.",
        inputRejected: "Die Eingabe wurde abgelehnt.",
        loadingFallback: "Wird geladen...",
        modelLoaded: "Modell geladen.",
        checkingModelResponse: "Modellantwort wird geprueft...",
        fallbackQuestionUsed: (errorMessage) => `Das Modell hat keine saubere Frage geliefert, daher wurde eine Fallback-Frage verwendet. ${errorMessage}`,
      },
      game: {
        localKnowledgeBaseReset: "Die lokale Wissensbasis wurde zurueckgesetzt.",
        savedTreeInvalid: "Der gespeicherte Baum sieht ungueltig aus. Setze den Seitenspeicher zurueck und versuche es erneut.",
        guessedIt: (animalLabel) => `Ich habe es erraten. Es ist ${animalLabel}.`,
        unknownAnimalLost: "Dann weiss ich es nicht. Ich habe verloren.",
        typeChosenAnimal: "Gib das Tier ein, das du gewaehlt hast.",
        sameAnimalCounts: "OK, das zaehlt auch. Ich habe es erraten!",
        inconsistentAnswer: "Diese Antwort wirkt inkonsistent. Gib einen einfachen Tiernamen auf Englisch ein.",
        savingNewQuestion: "Neue Frage wird gespeichert...",
        savedNewQuestion: (question) => `Gespeichert.\nNeue Frage: ${question}`,
        guessedAnimalQuestion: (animalLabel) => `Ist es ${animalLabel}?`,
        userYes: "Ja",
        userNo: "Nein",
        finished: {
          won: "Du hast gewonnen.",
          lost: "Du hast verloren.",
          cancelled: "Spiel abgebrochen.",
          invalid: "Das Spiel wurde mit einem ungueltigen Zustand beendet.",
          closed: "Die Spielsitzung ist beendet. Druecke F5, um neu zu starten.",
        },
      },
      ui: {
        pageTitle: "Browser LLM Demo",
        pageDescription: "Minimales Browser-Only-Grundgeruest zum Laden eines LLM-Providers und zum Starten eines kleinen Ja/Nein-Ratespiels.",
        languageLabel: "Sprache",
        languages: {
          en: "Englisch",
          de: "Deutsch",
        },
        restart: "Noch einmal spielen",
        startGameButton: "Spiel starten",
        debugStageLabel: "Phase",
        debugPromptLabel: "Prompt",
        debugResponseLabel: "Rohantwort",
        debugSendAgain: "Erneut senden",
        debugButton: "Debug",
        resetBaseButton: "Basis zuruecksetzen",
        gameTitle: "Spiel",
        statusTitle: "Status",
        lastModelCallTitle: "Letzter Modellaufruf",
        animalInputPlaceholder: "Tippe den Tiernamen auf Englisch ein",
        yesButton: "Ja",
        noButton: "Nein",
        saveButton: "Speichern",
        gameTryAgainButton: "Nochmal versuchen",
        gameCloseButton: "Spiel schliessen",
      },
      errors: {
        modelEngineNotReady: "Der LLM-Provider ist nicht bereit.",
        modelDidNotReturnJson: "Das Modell hat kein JSON-Objekt zurueckgegeben.",
        modelDidNotReturnYesNo: "Das Modell hat weder YES noch NO zurueckgegeben.",
        modelReturnedEmptyQuestion: "Das Modell hat eine leere Frage zurueckgegeben.",
        modelReturnedUnexpectedAnimals: "Das Modell hat unerwartete Tiernamen zurueckgegeben.",
        modelReturnedSameAnimals: "Das Modell hat dasselbe Tier fuer beide Zweige zugewiesen.",
        validatorReturnedEmptyQuestion: "Der Validator hat eine leere Frage zurueckgegeben.",
        modelReturnedEmptyHelloResponse: "Das Modell hat auf die Hello-Pruefung leer geantwortet.",
        webGpuUnavailable: "WebGPU ist in diesem Browser nicht verfuegbar. Verwende eine aktuelle Version von Chrome, Edge oder einen anderen Browser mit aktiviertem WebGPU.",
        fileProtocolUnsupported: "Diese Seite wird mit file:// geoeffnet. Starte die Demo aus C:\\work-poc\\portfolio\\local-llm-browser mit `python -m http.server 8080` und oeffne http://localhost:8080.",
        remoteConfigFetchFailed: (modelUrl, errorMessage) => `Die Remote-Modellkonfiguration von ${modelUrl} konnte nicht geladen werden. Urspruenglicher Fehler: ${errorMessage}`,
        remoteConfigUnavailable: (modelUrl) => `Die Remote-Modellkonfiguration ist unter ${modelUrl}/resolve/main/mlc-chat-config.json nicht erreichbar.`,
        remoteLibraryFetchFailed: (libraryUrl, errorMessage) => `Die Datei ${libraryUrl} konnte nicht geladen werden. Stelle sicher, dass model_lib.wasm existiert und ueber HTTP erreichbar ist. Urspruenglicher Fehler: ${errorMessage}`,
        remoteLibraryUnavailable: (libraryUrl) => `Die Remote-Modellbibliothek ist unter ${libraryUrl} nicht erreichbar.`,
      },
      prompts: {
        healthcheck: "hello",
        generateQuestion: (knownAnimal, newAnimal) => `You are a question generator for an animal guessing game.\n\nThe game needs one yes/no question that clearly distinguishes two animals.\n\nKnown animal:\n"${knownAnimal}"\n\nNew animal:\n"${newAnimal}"\n\nGenerate one short, general, factual question.\n\nRules:\n- The question must be answerable by "yes" or "no".\n- The question must separate the two animals reliably.\n- Prefer biological/category/physical/habitat traits.\n- Do NOT use animal-specific sounds like "Does it meow?" or "Does it bark?"\n- Do NOT mention either animal name directly.\n- Do NOT ask about subjective traits.\n- Do NOT ask about rare edge cases.\n- The question must be simple enough for a child.\n- Return only valid JSON.\n- Do not add explanations.\n\nBad examples:\n- "Does it meow?"\n- "Does it bark?"\n- "Is it cute?"\n- "Can it be a pet?"\n\nGood examples:\n- "Is it from the cat family?"\n- "Does it usually live in water?"\n- "Does it have hooves?"\n- "Is it a bird?"\n- "Does it have scales?"\n\nReturn format:\n{\n  "question": "...?",\n  "yesAnimal": "${knownAnimal} or ${newAnimal}",\n  "noAnimal": "${knownAnimal} or ${newAnimal}"\n}`,
        validateQuestion: (knownAnimal, newAnimal) => `You are a strict validator for an animal guessing game question.\n\nKnown animal:\n"${knownAnimal}"\n\nNew animal:\n"${newAnimal}"\n  \nDo not explain.\nthe answer for YOUR question should be\nYES - ${knownAnimal}\nNo - ${newAnimal}\n\ndo not use animal names in question\nRETURN only text of question`,
        sameAnimalCheck: (guessedAnimal, userAnimal) => `is "${guessedAnimal}" and "${userAnimal}" the same animal?\nsay yes or no\nno explanation\nno punctuation`,
        validateAnimalInput: (userInput) => `Decide whether the word "${userInput}" is a real common animal name.\nanswer YES if yes\nand NO if no\nNO explanation`,
      },
    };
  }
}
