export class GermanResources {
  getResources() {
    return {
      locale: "de",
      debug: {
        noModelCallYet: "Noch kein Modellaufruf.",
        noPromptYet: "Noch kein Prompt.",
        noResponseYet: "Noch keine Antwort.",
        emptyResponse: "[leere Antwort]",
        engineNotReady: "Der LLM-Provider ist nicht bereit.",
        promptEmpty: "Der Debug-Prompt ist leer.",
        runningEditedPrompt: "Bearbeiteter Debug-Prompt wird ausgefuehrt...",
        editedPromptCompleted: "Bearbeiteter Debug-Prompt abgeschlossen.",
        promptFailed: (errorMessage) => `Debug-Prompt fehlgeschlagen. ${errorMessage}`,
        stages: {
          healthCheck: "Gesundheitspruefung",
          gameValidateAnimalInput: "Spiel: Tiereingabe validieren",
          gameGenerateDistinguishingQuestion: "Spiel: Unterscheidungsfrage erzeugen",
          gameValidateGeneratedQuestion: "Spiel: Generierte Frage validieren",
          debugReplaySuffix: "Debug-Wiederholung",
        },
      },
      providers: {
        labels: {
          local: "lokaler WebLLM-Provider",
          echo: "Echo-Provider",
          openai: "OpenAI-kompatibler Provider",
        },
        status: {
          loading: (providerLabel) => `${providerLabel} wird geladen...`,
          connectingOpenAi: "Verbindung zur OpenAI-kompatiblen API wird aufgebaut...",
        },
        errors: {
          noProviderSelected: "Kein Provider ausgewaehlt.",
          unknownProviderType: (providerType) => `Unbekannter Provider-Typ: ${providerType}`,
          openAiBaseUrlMissing: "Der OpenAI-kompatible Provider benoetigt apiBaseUrl.",
          openAiApiKeyMissing: "Der OpenAI-kompatible Provider benoetigt einen API-Schluessel.",
          openAiModelMissing: "Der OpenAI-kompatible Provider benoetigt apiModel.",
          openAiRequestFailed: (status, details) => `Die OpenAI-kompatible Anfrage ist mit Status ${status} fehlgeschlagen. ${details}`,
          openAiInvalidResponse: "Der OpenAI-kompatible Provider hat eine ungueltige Antwort geliefert.",
        },
      },
      status: {
        waitingToStart: "Wartet auf den Start...",
        loadingResources: "Ressourcen werden geladen...",
        checkingProviderStatus: "Provider-Status wird geprueft...",
        waitingForProvider: "Warte auf den Provider...",
        sendingHelloPrompt: "Hello-Prompt wird gesendet und auf die Antwort des Providers gewartet...",
        readyToStartGame: "Der Provider ist bereit. Starte das Spiel, wenn du bereit bist.",
        loadingFallback: "Wird geladen...",
        modelLoaded: "Modell geladen.",
        checkingModelResponse: "Modellantwort wird geprueft...",
      },
      game: {
        messages: {
          roundStarted: "Lass uns spielen. Denke an ein Tier und ich versuche es zu erraten.",
          animalGuessQuestion: (animalLabel) => `Ist es ${animalLabel}?`,
          branchQuestionFallback: "Antworte mit Ja oder Nein.",
          lostAskAnimal: "Ich konnte dein Tier nicht erraten. An welches Tier hast du gedacht?",
          validatingAnimalInput: "Lass mich das kurz pruefen...",
          invalidAnimalInput: "Sehr witzig. Nenne mir einen eindeutigen, gaengigen Tiernamen auf Englisch, der sich von meinem letzten Vorschlag unterscheidet.",
          generatingQuestion: "Lass mich darueber nachdenken...",
          validatingQuestion: "Einen Moment, ich pruefe etwas...",
          savingLearning: "Fast fertig...",
        },
        finished: {
          won: "Ich habe es erraten!",
          lost: "Ich habe dein Tier diesmal nicht erraten.",
          cancelled: "Spiel abgebrochen.",
          invalid: "Etwas ist schiefgelaufen, deshalb musste ich diese Runde beenden. Du kannst es erneut versuchen.",
          closed: "Die Spielsitzung ist beendet. Druecke F5, um neu zu starten.",
        },
      },
      ui: {
        pageTitle: "Browser LLM Demo",
        pageDescription: "Minimales Browser-Only-Grundgeruest zum Laden eines LLM-Providers und zum Starten eines kleinen Ja/Nein-Ratespiels.",
        languageLabel: "Sprache",
        languages: {
          en: "Englisch",
          de: "Deutsch",
        },
        restart: "Noch einmal spielen",
        startGameButton: "Spiel starten",
        debugStageLabel: "Phase",
        debugPromptLabel: "Prompt",
        debugResponseLabel: "Rohantwort",
        debugSendAgain: "Erneut senden",
        debugButton: "Debug",

        gameTitle: "Spiel",
        statusTitle: "Status",
        lastModelCallTitle: "Letzter Modellaufruf",
        animalInputPlaceholder: "Tippe den Tiernamen auf Englisch ein",
        yesButton: "Ja",
        noButton: "Nein",
        saveButton: "Speichern",
        gameTryAgainButton: "Nochmal versuchen",
        gameCloseButton: "Spiel schliessen",
      },
      errors: {
        modelEngineNotReady: "Der LLM-Provider ist nicht bereit.",
        modelDidNotReturnJson: "Das Modell hat kein JSON-Objekt zurueckgegeben.",
        modelDidNotReturnYesNo: "Das Modell hat weder YES noch NO zurueckgegeben.",
        modelReturnedEmptyQuestion: "Das Modell hat eine leere Frage zurueckgegeben.",
        modelReturnedUnexpectedAnimals: "Das Modell hat unerwartete Tiernamen zurueckgegeben.",
        modelReturnedSameAnimals: "Das Modell hat dasselbe Tier fuer beide Zweige zugewiesen.",
        validatorReturnedEmptyQuestion: "Der Validator hat eine leere Frage zurueckgegeben.",
        modelReturnedEmptyHelloResponse: "Das Modell hat auf die Hello-Pruefung leer geantwortet.",
        webGpuUnavailable: "WebGPU ist in diesem Browser nicht verfuegbar. Verwende eine aktuelle Version von Chrome, Edge oder einen anderen Browser mit aktiviertem WebGPU.",
        fileProtocolUnsupported: "Diese Seite wird mit file:// geoeffnet. Fuehre im Projektverzeichnis `python -m http.server 8080` aus und oeffne http://localhost:8080.",
        remoteConfigFetchFailed: (modelUrl, errorMessage) => `Die Remote-Modellkonfiguration von ${modelUrl} konnte nicht geladen werden. Urspruenglicher Fehler: ${errorMessage}`,
        remoteConfigUnavailable: (modelUrl) => `Die Remote-Modellkonfiguration ist unter ${modelUrl}/resolve/main/mlc-chat-config.json nicht erreichbar.`,
        remoteLibraryFetchFailed: (libraryUrl, errorMessage) => `Die Datei ${libraryUrl} konnte nicht geladen werden. Stelle sicher, dass model_lib.wasm existiert und ueber HTTP erreichbar ist. Urspruenglicher Fehler: ${errorMessage}`,
        remoteLibraryUnavailable: (libraryUrl) => `Die Remote-Modellbibliothek ist unter ${libraryUrl} nicht erreichbar.`,
      },
      prompts: {
        healthcheck: "hello",
        game: {
          validateAnimalInput: (failedAnimalName, userInput) => `SYSTEM:\nYou validate user input for an animal guessing game.\n\nTASK:\nDecide whether USER_INPUT is:\n1. a real common animal name in English\n2. different from FAILED_ANIMAL_NAME\n\nRULES:\n- Accept only a common animal name in English.\n- Reject mythical creatures, jobs, objects, places, adjectives, or vague categories.\n- Reject if it is the same animal as FAILED_ANIMAL_NAME.\n- Prefer singular common names.\n- Return JSON only.\n- Do not add explanation outside JSON.\n\nINPUT:\nFAILED_ANIMAL_NAME: "${failedAnimalName}"\nUSER_INPUT: "${userInput}"\n\nRETURN JSON ONLY:\n{\n  "isValid": true,\n  "normalizedAnimal": "whale",\n  "reasonCode": "valid"\n}`,
          generateDistinguishingQuestion: (failedAnimalName, userAnimalName, previousQuestionsJson) => `SYSTEM:\nYou generate one yes/no question for an animal guessing game.\n\nTASK:\nCreate one short distinguishing yes/no question between FAILED_ANIMAL_NAME and NEW_ANIMAL_NAME.\n\nRULES:\n- The question must be answerable by yes or no.\n- The question must distinguish these two animals.\n- Do not mention either animal name in the question.\n- Prefer simple, stable, factual traits.\n- Avoid rare exceptions.\n- Avoid subjective wording.\n- Avoid duplicate or near-duplicate questions from PREVIOUS_QUESTIONS.\n- Return exactly one candidate mapping.\n- Return JSON only.\n\nINPUT:\nFAILED_ANIMAL_NAME: "${failedAnimalName}"\nNEW_ANIMAL_NAME: "${userAnimalName}"\nPREVIOUS_QUESTIONS:\n${previousQuestionsJson}\n\nRETURN JSON ONLY:\n{\n  "question": "Does it live in water?",\n  "yesAnimal": "whale",\n  "noAnimal": "cat"\n}`,
          validateGeneratedQuestion: (failedAnimalName, userAnimalName, candidateQuestion, declaredYesAnimal, declaredNoAnimal) => `SYSTEM:\nYou validate a candidate yes/no question for an animal guessing game.\n\nTASK:\nCheck whether CANDIDATE_QUESTION correctly distinguishes FAILED_ANIMAL_NAME and NEW_ANIMAL_NAME, and whether the yes/no mapping is valid.\n\nRULES:\n- The question must be a yes/no question.\n- The question must not contain animal names directly.\n- The question should clearly distinguish the two animals.\n- The declared yes/no mapping must be logically consistent.\n- Return JSON only.\n\nINPUT:\nFAILED_ANIMAL_NAME: "${failedAnimalName}"\nNEW_ANIMAL_NAME: "${userAnimalName}"\nCANDIDATE_QUESTION: "${candidateQuestion}"\nDECLARED_YES_ANIMAL: "${declaredYesAnimal}"\nDECLARED_NO_ANIMAL: "${declaredNoAnimal}"\n\nRETURN JSON ONLY:\n{\n  "isValid": true,\n  "normalizedQuestion": "Does it live in water?",\n  "yesAnimal": "whale",\n  "noAnimal": "cat",\n  "reasonCode": "valid"\n}`,
        },
      },
    };
  }
}
